version: 2.1

orbs:
  javascript: whoop/javascript@2

jobs:
  build:
    executor:
      name: javascript/docker
      executor_docker_image: cimg/node:14.10.1
      working_directory: ~/js-buy-sdk

    steps:
      - checkout

      - javascript/npm-nexus-auth:
          nexus_repository_name: "npm-group"

      - run:
          name: Build
          command: |
            yarn
            yarn run build

      - javascript/bump-package-version:
          base_package_version: "2.20"

      - run:
          name: cat
          command: |
            cat package.json

      - run:
          name: npm config ls -l
          command: |
            npm config ls -l

      - javascript/publish-to-nexus:
          nexus_repository_name: "npm-private"

      - javascript/change-publish-registry-to-codeartifact:
          code_artifact_repository_name: "whoop-npm"

      - javascript/authenticate-with-codeartifact

      - javascript/npm-codeartifact-auth:
          code_artifact_repository_name: "whoop-npm"

      - javascript/publish-to-codeartifact:
          code_artifact_repository_name: "whoop-npm"

workflows:
  build_and_test:
    jobs:
      - build:
          context: environment-variables
