version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.10.1

    working_directory: ~/js-buy-sdk

    steps:
      - checkout

      - run:
          name: Log into nexus npm registry
          command: ./npm-login.sh

      - run:
          name: Build
          command: |
            yarn
            yarn run build

      - run:
          name: Publish to nexus
          command: |
            npm publish

workflows:
  build_and_test:
    jobs:
      - build:
          context: environment-variables
