#!/bin/bash

set -e

NODE_VERSION=$(node -v)

echo <<MESSAGE
***********************************
  -- DEPS --
  NODE VERSION: $NODE_VERSION
  NPM VERSION: $(npm -v)
***********************************
MESSAGE

versioned_node_modules_path="node_modules_${NODE_VERSION}"

if [ ! -d "${versioned_node_modules_path}" ]; then
  mkdir "$versioned_node_modules_path"
fi

if [ -L node_modules ]; then
  rm node_modules
fi

ln -s "$versioned_node_modules_path" node_modules

# See: https://github.com/npm/npm/issues/11283
npm set progress=false

# Install deps
npm install
