#!/bin/bash -l

set -e

setup_node () {
  nvm install $1
  nvm alias default $1
}

case $CIRCLE_NODE_INDEX in
  0)
    setup_node $NODE_4_VERSION
    ;;
  1)
    setup_node $NODE_5_VERSION
    ;;
  *)
    setup_node $NODE_5_VERSION
    ;;
esac
