#!/bin/sh

set -x

export PATH=$(npm bin):$PATH

git checkout master -- src

yuidoc -t ./yuidoc/theme

rm -rf src

git reset -- src

for file in $(find api -name '*.html'); do
  echo "---\nlayout: api\n---\n\n\n$(cat $file)" > $file
done
