#!/usr/bin/env node
"use strict";

const docBuilder = require('./util/doc-builder');
const commandLineOptions = require('commander')
  .option('-r, --references <items>', 'Comma separated list of GIT tags or branches. For example, to generate docs for master, v0.2.1 and v0.2.2, use, `npm run doc:build -- --references master,v0.2.1,v0.2.2`', val => val.split(','))
  .parse(process.argv);

let docBuilderOptions = {
  requestedReferenceNames: commandLineOptions.references
};

console.log('Building ....\n');
docBuilder(docBuilderOptions).then(() => {
  console.log('\nDone building');
}).catch(error => {
  console.error('\nError', error);
});
