#!/usr/bin/env node

/* globals require process */

require('./util/work-from-root')();

var fse = require('fs-extra');
var buildProject = require('./util/build-project');

var buildPath = 'dist';

fse.removeSync(buildPath);

process.env.BROCCOLI_ENV = 'production';

buildProject(buildPath, function (buildStatus) {
  process.exit(buildStatus);
});
