#!/usr/bin/env node

/* eslint-env node */

require('./util/work-from-root')();

var fsExtra = require('fs-extra');
var buildProject = require('./util/build-project');
var buildDoc = require('./util/build-doc');

var buildPath = 'dist';

fsExtra.removeSync(buildPath);

process.env.BROCCOLI_ENV = 'production';

buildProject(buildPath, function (buildStatus) {
  process.exit(buildStatus);
});

buildDoc(function (error) {
	if (error) {
		console.error(error);
	}
});