#!/usr/bin/env node

/* globals require process */

require('./util/work-from-root')();

var docBuilder = require('./util/doc-builder')({
  docsBranchName: 'gh-pages',
  rmSrcDir: true,
  commitDocs: true
});

console.log('Building ....');
docBuilder.build().then(() => {
  console.log('\nDone building');
}).catch(error => {
  console.error('error', error);
});
