#!/usr/bin/env node

/* globals require process */

require('./util/work-from-root')();

var fsExtra = require('fs-extra');
var fs = require('fs');
var buildProject = require('./util/build-project');
var npmDo = require('./util/npm-do');

var testBuildPath = '.dist-test';

fsExtra.removeSync(testBuildPath);

buildProject(testBuildPath, function (buildStatus) {
  if (buildStatus === 0) {
    var xunitWriteStream = fs.createWriteStream('tests.xml');

    xunitWriteStream.on('open', function() {
      npmDo('testem', ['ci', '-R', 'xunit'], function (testStatus) {
        process.exit(testStatus);
      }, { stdio: ['ignore', xunitWriteStream, process.stderr] });
    });
  } else {
    process.exit(buildStatus);
  }
});
