#!/usr/bin/env node

/* globals require process */
require('./util/work-from-root')();

var fse = require('fs-extra');

var libPath = 'lib';
var buildPath = 'dist';

fse.removeSync(libPath);
fse.removeSync(buildPath);
