#!/usr/bin/env node

/* globals require process */
require('./util/work-from-root')();

var fsExtra = require('fs-extra');
var buildProject = require('./util/build-project');
var path = require('path');

var libPath = 'lib';
var buildPath = 'dist';

fsExtra.removeSync(libPath);
fsExtra.removeSync(buildPath);

process.env.BROCCOLI_ENV = 'production';

buildProject(buildPath, function (buildStatus) {
  if (buildStatus === 0) {
    var srcDir = path.join(process.cwd(), 'dist', 'node-lib');
    var destDir = path.join(process.cwd(), 'lib');

    fsExtra.copySync(srcDir, destDir);

    process.exit(0);
  }

  process.exit(buildStatus);
});
