#!/usr/bin/env node

/* globals require process */
require('./util/work-from-root')();

var cleanDirectory = require('./util/clean-directory');
var recursiveCpdir = require('./util/recursive-cpdir');
var buildProject = require('./util/build-project');
var path = require('path');

var libPath = 'lib';
var buildPath = 'dist';

cleanDirectory(libPath);
cleanDirectory(buildPath);

process.env.BROCCOLI_ENV = 'production';

buildProject(buildPath, function (buildStatus) {
  if (buildStatus === 0) {
    var srcDir = path.join(process.cwd(), 'dist', 'node-lib');
    var destDir = path.join(process.cwd(), 'lib');

    recursiveCpdir(srcDir, destDir);

    process.exit(0);
  }

  process.exit(buildStatus);
});
