#!/usr/bin/env node

/* globals require process */

require('./util/work-from-root')();

var followProcess = require('./util/follow-process');
var binPath = require('./util/node-module-bin-path');
var cleanDirectory = require('./util/clean-directory');
var buildProject = require('./util/build-project');

var testBuildPath = '.dist-test';

cleanDirectory(testBuildPath);


buildProject(testBuildPath, function (buildStatus) {
  if (buildStatus === 0) {
    followProcess('node', [binPath('testem'), 'ci'], function (testStatus) {
      process.exit(testStatus);
    });
  } else {
    process.exit(buildStatus);
  }
});
