#!/usr/bin/env node

/* globals require process */

require('./util/work-from-root')();

var fsExtra = require('fs-extra');
var buildProject = require('./util/build-project');
var npmDo = require('./util/npm-do');

var testBuildPath = '.dist-test';

fsExtra.removeSync(testBuildPath);


buildProject(testBuildPath, function (buildStatus) {
  if (buildStatus === 0) {
    npmDo('testem', ['ci'], function (testStatus) {
      process.exit(testStatus);
    });
  } else {
    process.exit(buildStatus);
  }
});
