#!/bin/sh

set -x

export PATH=$(npm bin):$PATH

git --work-tree=./docs checkout master -- src

# settings for yuidoc will come from yuidoc.json
yuidoc

rm -rf ./docs/src

git reset -- docs/src

# the following will append
# 
# ---
# layout: api
# ---
# 
# To the start of all html files in the api folder for Jekyll theming purposes
for file in $(find docs/api -name '*.html'); do
  echo "---\nlayout: api\n---\n\n\n$(cat $file)" > $file
done
