#!/bin/bash

set -e

echo <<MESSAGE

***********************************

  -- DEPS --

  NODE VERSION: $(node -v)

  NPM VERSION: $(npm -v)

***********************************

MESSAGE

# Versions differ intentionally. NPM package at 2.1.6 contains phantom 2.1.1
curl -k -L -o phantomjs.tar.bz2 https://s3.amazonaws.com/travis-phantomjs/phantomjs-${PHANTOMJS_VERSION}-ubuntu-12.04.tar.bz2
tar -jxf phantomjs.tar.bz2

# Grab selenium standalone
curl -k -L -o selenium-standalone.jar http://goo.gl/IHP6Qw

versioned_node_modules_path="node_modules_${CIRCLE_NODE_INDEX}"

if [ ! -d "${versioned_node_modules_path}" ]; then
  mkdir $versioned_node_modules_path
fi

if [ -L node_modules ]; then
  rm node_modules
fi

ln -s $versioned_node_modules_path node_modules

npm install
