#!/bin/bash

set -e

echo <<MESSAGE

***********************************

  -- DEPS --

  NODE VERSION: $(node -v)

  NPM VERSION: $(npm -v)

***********************************

MESSAGE

# Versions differ intentionally. NPM package at 2.1.6 contains phantom 2.1.1
curl -k -L -o phantomjs.tar.bz2 https://s3.amazonaws.com/travis-phantomjs/phantomjs-${PHANTOMJS_VERSION}-ubuntu-12.04.tar.bz2
tar -jxf phantomjs.tar.bz2

npm install
