#!/bin/bash

set -x

echo <<MESSAGE

***********************************

  -- TEST --

  NODE VERSION: $(node -v)

  NPM VERSION: $(npm -v)

***********************************

MESSAGE

(npm run test-ci)
qunit_tests_status=$?
(npm run test-examples)
wdio_tests_status=$?

mkdir -p $CIRCLE_TEST_REPORTS/xunit

mv tests.xml $CIRCLE_TEST_REPORTS/xunit/
mv WDIO.*.xml $CIRCLE_TEST_REPORTS/xunit/

exit $qunit_tests_status || $wdio_tests_status
