#!/bin/bash

set -e

echo <<MESSAGE

***********************************

  -- TEST --

  NODE VERSION: $(node -v)

  NPM VERSION: $(npm -v)

***********************************

MESSAGE

npm run test-ci
npm run test-examples

mkdir -p $CIRCLE_TEST_REPORTS/xunit

mv tests.xml $CIRCLE_TEST_REPORTS/xunit/
mv WDIO.*.xml $CIRCLE_TEST_REPORTS/xunit/
