name: Run CI tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup node and npm
      uses: actions/setup-node@v3
      with:
        cache: npm
    - name: NPM install
      run: npm ci
      shell: bash
    - run: npm test

